package com.davidsperling.onegam1.song;

public enum SongEvent {
	SAY_SHOOT_UP, SAY_SHOOT_DOWN, SAY_SHOOT_LEFT, SAY_SHOOT_RIGHT,
	SAY_BLOCK_UP, SAY_BLOCK_DOWN, SAY_BLOCK_LEFT, SAY_BLOCK_RIGHT,
	
	DO_SHOOT_UP, DO_SHOOT_DOWN, DO_SHOOT_LEFT, DO_SHOOT_RIGHT,
	DO_BLOCK_UP, DO_BLOCK_DOWN, DO_BLOCK_LEFT, DO_BLOCK_RIGHT,
	
	TITLE_CARD, HOLD, REST, END
}
